//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleMovimiento
    {
        public int Id { get; set; }
        public int IdRegistroMovimiento { get; set; }
        public int IdServicioProducto { get; set; }
        public int Cantidad { get; set; }
        public decimal PrecioAplicado { get; set; }
        public decimal Subtotal { get; set; }
    
        public virtual Registro_Movimientos Registro_Movimientos { get; set; }
        public virtual Servicio_Repuesto Servicio_Repuesto { get; set; }
    }
}
