//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EDM : DbContext
    {
        public EDM()
            : base("name=EDM")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auditoria> Auditoria { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<DetalleMovimiento> DetalleMovimiento { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Modelo> Modelo { get; set; }
        public virtual DbSet<Registro_Movimientos> Registro_Movimientos { get; set; }
        public virtual DbSet<Servicio_Repuesto> Servicio_Repuesto { get; set; }
        public virtual DbSet<TipoOperacion> TipoOperacion { get; set; }
    
        public virtual ObjectResult<Nullable<int>> Modelo_Save(string xMLModelo, string xmlUsuario)
        {
            var xMLModeloParameter = xMLModelo != null ?
                new ObjectParameter("XMLModelo", xMLModelo) :
                new ObjectParameter("XMLModelo", typeof(string));
    
            var xmlUsuarioParameter = xmlUsuario != null ?
                new ObjectParameter("xmlUsuario", xmlUsuario) :
                new ObjectParameter("xmlUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Modelo_Save", xMLModeloParameter, xmlUsuarioParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Modelo_Update(string xMLModelo, string xmlUsuario)
        {
            var xMLModeloParameter = xMLModelo != null ?
                new ObjectParameter("XMLModelo", xMLModelo) :
                new ObjectParameter("XMLModelo", typeof(string));
    
            var xmlUsuarioParameter = xmlUsuario != null ?
                new ObjectParameter("xmlUsuario", xmlUsuario) :
                new ObjectParameter("xmlUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Modelo_Update", xMLModeloParameter, xmlUsuarioParameter);
        }
    
        public virtual int RethrowError()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RethrowError");
        }
    }
}
