//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro_Movimientos
    {
        public int Id { get; set; }
        public int IdCliente { get; set; }
        public int IdModelo { get; set; }
        public string Observaciones { get; set; }
        public int IdTipoOperacion { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual TipoOperacion TipoOperacion { get; set; }
    }
}
