//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoOperacion
    {
        public TipoOperacion()
        {
            this.Registro_Movimientos = new HashSet<Registro_Movimientos>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Registro_Movimientos> Registro_Movimientos { get; set; }
    }
}
