<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net4.8.1</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Entidades\Modelo.edmx" />
  </ItemGroup>

  <ItemGroup>
    <EntityDeploy Include="Entidades\Modelo.edmx">
      <Generator>EntityModelCodeGenerator</Generator>
      <LastGenOutput>Modelo.Designer.cs</LastGenOutput>
    </EntityDeploy>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Security" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Utilities\Utilities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Entidades\Modelo.Context.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Modelo.Context.tt</DependentUpon>
    </Compile>
    <Compile Update="Entidades\Modelo.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Modelo.tt</DependentUpon>
    </Compile>
    <Compile Update="Entidades\Modelo.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Modelo.edmx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Entidades\Modelo.Context.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Modelo.Context.cs</LastGenOutput>
    </None>
    <None Update="Entidades\Modelo.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Modelo.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

</Project>
